---
title: "Modularity"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Modularity}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r suppressMessages=T, echo=F}
library(ramp.micro)
```

This software has a modular design with two components. Modularity in the design is implemented using one of R's basic basic object oriented methods, the `S3 Class.` 

In a nutshell, there are two dynamical components: 

+ The **M** component describes adult mosquito population dynamics

+ The **L** component describes aquatic mosquito population dynamics

To develop a modular simulation framework, each dynamical component defines a common set of functions that are called. Each module in the class defines its own `S3` method. 

## **M** Component

### Methods 

+ `setup_adult_model` 

    + `make_Psi_*` 

    + `setup_dispersal_*` 

    + `setup_bionomics_*` 

    + `make_demography_*` 
    
+ `save_states_M` 

+ `compute_diffs_M` 

+ `init_states_M` 

+ `init_adult_model` is a wrapper that calls `init_adult_model_*` 




### Modules

There are currently two 

## **L** Component

### Setup 

### Methods 

### Modules
